[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "heisenberg-ion"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "pyyaml"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["heisenberg_ion*"]